project:
  type: website
  render:
    - "index.qmd"

website:
  title: "ABC"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



