project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "lecture.qmd"

website:
  title: "Finansteori"
  navbar:
    left:
      - text: "Indeks"
        href: index.qmd
      - text: "Timeplan"
        href: lecture.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



