---
title: "Finansteori (SFB30820)"
subtitle: "Beregninger"
author: "Jørn I.Halvorsen"
date: "2021/08/12 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    includes:
      in_header: "mathjax-equation-numbers.html"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
#output: 
#  html_notebook:
#  toc: false
---

```{r xaringan-tile-view, echo=FALSE}
xaringanExtra::use_tile_view()
#xaringanExtra::use_share_again()
xaringanExtra::use_scribble()
xaringanExtra::use_webcam()
```

```{r eval=FALSE, include=FALSE}
Sys.which('decktape')
#xaringan::decktape("presentations.html", output="abc.pdf")
xaringan::inf_mr("tavlefil.Rmd")
```

# NÅ 

Eksempel 2.6

```{r, eval=T, echo=F}
w <- c(0.30, 0.40, 0.30)
df_eks_2_6 <- data.frame(aksje=c("A","B","C"),erp=c(0.12,0.15,0.25),std=c(0.10,0.20,0.40),korr=c(0.8,-0.1,0.5))
htmlTable(df_eks_2_6, header=c("Aksje","Forventet avkastning","Standardavvik","Korrelasjonskoeffisient"))
```

Hvor investert beløp vektene er gitt ved `r w`

Ved innsetting av formelen gir dette oss

\begin{equation*}
Var(r_p)=(0.30)^20.10^2+(0.40)^20.20^2+(0.3)^20.40^2 + \\
2\cdot 0.30_b0.10\cdot 0.2 \cdot 0.8+\\
2\cdot 0.30_c0.10Std(c)\cdot -0.1+\\
2\cdot 0.40\cdot 0.30.2\cdot 0.4\cdot 0.5 = 0.02722
\end{equation*}

\begin{equation*}
Std(r_p)=\sqrt{0.02722}=0.1649848
\end{equation*}

---

