---
title: ""
output: github_document
---

## Anbefalte oppgaver

```{r echo=F}
source(paste0(rprojroot::find_rstudio_root_file(),'/inst/forelesningsnotater/timeplan.R'))
cns <- c("Forelesnin","Eksamen og arbeidskrav","Fra bok","Fra nettside")
kableExtra::kbl(df2,col.names=cns) %>% kableExtra::kable_paper(full_width = F) %>% kableExtra::kable_styling(font_size=12, )
```

## Tidligere eksamensoppgaver

[Eksamen 2022](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/Finansteori%20(SFB30820)%2C%20H%C3%B8sten%202022.pdf)

[Eksamen 2022 (løsningsforslag)](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/Finansteori%20(SFB30820)%2C%20H%C3%B8sten%202022_losningsforslag.pdf)

[Eksamen 2021](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-10.12.2021.pdf)

[Eksamen 2021 (løsningsforslag)](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-10.12.2021_losningsforslag_JIH.pdf)

[Eksamen 2020](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-24.11.2020.pdf)

[Eksamen 2020 (løsningsforslag)](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb-finansteori-2020_losning.pdf)


## Fra lærebok og nettside

[Lenke til bokens nettside](https://finans2.portfolio.no/)


```{r, echo=F}
knitr::knit_exit()
```


## Oppgaveløsning etter forelesning

**31.8 fra kl. 12:15**

Eksamensoppgave 2021: 
Oppgave 1, spørsmål 1 og 2. Oppgave 2

Eksamensoppgave 2022: 
Oppgave 1, spørsmål 1. Oppgave 2

Eksamensoppgave 2020: 
Oppgave 1

[Mappe til løsningsforslag](https://github.com/joernih/SFB30820Finansteori/tree/main/inst/eksamensoppgaver/losningsforslag)
## Tidligere eksamensoppgaver

[Eksamen 2021](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-10.12.2021.pdf)

[Eksamen 2021 (løsningsforslag)](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-10.12.2021_losningsforslag_JIH.pdf)

[Eksamen 2022 kontinuasjon](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/Exam_SFB30820_Finansteori_C_S2022.pdf)

[Eksamen 2022 kontinuasjon (løsningsforslag)](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/Exam_SFB30820_Finansteori_C_S2022_Solution_Proposal.pdf)

[Eksamen 2020](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-24.11.2020.pdf)

[Eksamen 2020 (løsningsforslag)](https://github.com/joernih/SFB30820Finansteori/blob/main/inst/eksamensoppgaver/sfb30820-finansteori-24.11.2020_losningsforslag_JIH.pdf)


