---
title: "Finansteori (SFB30820), Høsten 2021"
output:
  html_notebook:
    css: css/ON.css
---

```{r eval=FALSE, include=FALSE}
# Oppgave 1
## a)
w <- 0.5714
sjekk_1 <- 0.06*w + (1-w)*0.13
## b)
w <- 0.928
sjekk_2 <- 0.06*w + (1-w)*0.13
## c)
w <- 81/106
sjekk_3 <- 200*w - 648*(1-w)

# Oppgave 2
## a)
### Obli A
kr <- 300*0.04
ut <- 300
sr <- 0.06
kr/(1+sr)+kr/(1+sr)^2 + ut/(1+sr)^2
### Obli B
kr <- 300*0.04
ut <- 300
sr <- 0.06
kr/(1+sr)+kr/(1+sr)^2+kr/(1+sr)^3+ut/(1+sr)^3
### Obli C
kr <- 300*0.05i
ut <- 300.
sr <- 0.06
kr/(1+sr)+kr/(1+sr)^2+kr/(1+sr)^3+ut/(1+sr)^3

## b)
ef_a <- (100/87.63)^(1/3)
ef_b <- (100/87.63)^(1/2)

100/(ef_a)^3
100/(ef_b)^2

# Oppgave 3
w_m <- 0.01/0.06
kvsjekk_m <- w_m*0.03+(1-w_m)*0.09
w_b <- 0.04/0.09
kvsjekk_b <- w_b*0.03+(1-w_b)*0.12
# std
(1-w_m)*12
(1-w_b)*15
# beta
#0.12=0.03+beta_b*(0.09-0.03)
beta_b = (0.12-0.03)/(0.09-0.03)
kon_b <- 0.03+beta_b*(0.09-0.03)
kon_abc <- 0.01+beta_b*(0.09-0.01)

# Oppgave 4
N <-100000
M <- 50000
n <- N/M
Pe <- 15
P0 <- 10
Px <- (100000*Pe+50000*10)/(50000+100000)
Px-Pe
Tx <- (Pe-P0)/(n+1)
```


# Oppgave 1: Porteføljeteori (Teller 30 prosent) 

De to kameratene Lars og Sigurd har begge investert i aksjen til oljeselskapet Star Oil og i 
aksjen til reiselivsbedriften Travel. Lars sin forventede porteføljeavkastning er 9 prosent og 
Sigurd har en forventet porteføljeavkastning på 6,5 prosent. De to aksjene har følgende karakteristika:  Travel Star oil  Forventet avkastning 6 13 Avkastningens standardavvik 10 18                          Korrelasjonskoeffisienten mellom avkastningen på de to aksjene er null.  


a) Hva er den initiale porteføljestrukturen til Lars? 

<div class="solution">
$$
0.09 = 0.06w + 0.13(1-w) \\
0.06w-0.13w = 0.09 -0.13 \\
-0.07w = -0.04 \\
w = 0.04/0.07 \\
w = 0.5714
$$
</div>



b) Hva er den initiale porteføljestrukturen til Sigurd? 

<div class="solution">
<!-- 0.065 = 0.0*0.928 + 0.13*(1-0.928) -->

$$
0.065 = 0.06w + 0.13(1-w) \\
0.06w-0.13w = 0.065 -0.13 \\
-0.07w = -0.065 \\
w = 0.065/0.07 \\
w = 0.928
$$
</div>



c) Hva er de risikominimerende porteføljeandelene i en portefølje som består av aksjer i 
selskapene Star Oil og Travel? 

<div class="solution">

$$
Min _w Var(r_p) = w^2\cdot 10^2 + (1-w)^2\cdot 18^2 \\
\text{første ordens betingelsen} \\
200 w - 648 (1 - w) = 0 \\
w = 81/106 = 0.76
$$
</div>


d) Hva er gevinstene for Lars og Sigurd ved å effektivisere sine porteføljer? Gi en verbal 
forklaring på hvordan de to kameratene kan ha ulik effekt på forventet 
porteføljeavkastning når de effektiviserer sine porteføljer   

<div class="solution">
Det å gå mot en effisient portefølje er kjennetegnet ved at Lars eller Sigrud kan oppnå en gevinst form av økt forventet avkastning og/eller få redusert sin risiko ved å endre sin porteføljesammensetning. Når det er oppnådd, vil det være graden av risikoaversjon som vil være bestemmende for hvilket sett man vil velge, og derfor kunne forklare hvorfor effekten på forventet avkastning vil være forskjellig mellom Lars og Sigurd.  
</div>

# Oppgave 2: Obligasjoner (Teller 20 prosent) 

På Seychellene har myndighetene investert betydelig i havneområdet og utviklet en dyphavn 
som både kan to imot cruiseskip og containerskip, og slik legger til rette både for økt turisme 
og økt vareeksport. De har finansiert investeringene med 3 obligasjonslån med følgende 
karakteristika: Lån Pålydende (Tall i mill.)  Kupongrente Gjenværende 
Løpetid (År) A 300  4 2 B 300  4 3 C 300  5 3 Samtidig ser rentekurven ut som følger:  Spotrente år 1 Spotrente år 2 Spotrente år 3 6 6 6  
2  

a) Anta at obligasjoner prises med en standard nåverditilnærming. Hva er dagens 
markedspris på de tre obligasjonene?    

<div class="solution">
$$
P_{0,A} = \frac{300\cdot 0.04}{(1+0.06)^{1}} + \frac{300\cdot 0.04}{(1+0.06)^{2}} + \frac{300}{(1+0.06)^3} =  288.9996 \\
P_{0,B} = \frac{300\cdot 0.04}{(1+0.06)^{1}} + \frac{300\cdot 0.04}{(1+0.06)^{2}} + \frac{300\cdot   0.04}{(1+0.06)^{3}}+\frac{300}{(1+0.06)^3}  = 283.9619  \\
P_{0,C} = \frac{300\cdot 0.05}{(1+0.06)^{1}} + \frac{300\cdot 0.05}{(1+0.06)^{2}} + \frac{300\cdot 0.05}{(1+0.06)^{3}}+\frac{300}{(1+0.06)^3}  = 251.88
$$
</div>

På Seychellene er det to store obligasjonsfond, Korallen og Palmen. Obligasjonsfondet 
Palmen har et avkastningskrav på 7 prosent. Obligasjonsfondet Korallen har et 
avkastningskrav på 3 prosent.   De to fondene har mulighet til å investere i to null-kupong obligasjoner som begge har 
pålydende 100 euro. Obligasjon A har en løpetid på 3 år og handles i dag til en pris på 87,63 
euro. Obligasjon B har en løpetid på 2 år og handles i dag til en pris på 87,34 euro.  

b) Hvilke (om noen) av disse to obligasjonene vil de to fondene Palmen og Korallen 
investere i ? 

<div class="solution">
Obligasjon A
$$
87.63=\frac{100}{(1+r)^3}  \Leftrightarrow \\
(1+r)^3=\frac{100}{87.63} \\
(1+r)=(\frac{100}{87.63})^{1/3}=1.044999
$$
</div>

<div class="solution">
Obligasjon B
$$
87.34=\frac{100}{(1+r)^2}  \Leftrightarrow \\
(1+r)^2=\frac{100}{87.34} \\
(1+r)=(\frac{100}{87.34})^{1/2}=1.068252
$$
<br>
Palmen krav 7 prosent, hverken obligasjon A eller B siden ingen er høyere enn avkastningskravet.
<br>
Koralen krav 3 prosent, både obligasjon A og B tilfredstiller avkastningskravet, men B har høyest, vil derfor investere alt der.
</div>



c) Gi en verbal forklaring på forholdet mellom pålydende verdi og markedspris på både 
null-kupong obligasjoner og på kupong obligasjoner.  

<div class="solution">
-Null-kupong: Hvor mange ganger mer man får betalt tre år fram i tid (i form av restbeløpet) ved å investere én krone i dag. 

-Kupong obligasjoner: Hvor mange ganger mer man får betalt i løpet av obligasjonenss løpetid (i form av kupongrente og restbeløp) ved å investere én krone i dag. 
</div>


# Oppgave 3: CAPM og porteføljer (Teller 30 prosent) 

a) Gi en verbal forklaring på hva som menes med kapitalverdimodellen (CAPM). Kommenter spesielt hvilken rolle risikofrirente spiller i kapitalverdimodellen. Anta at forutsetningene som ligger til grunn for CAPM holder. 

<div class="solution">
Kapitalverdimodellen (KVM) er en modell til prisetting av risiko (forholdet mellom systemtatisk risiko og kapitalkost). Vi bruker KVM til å finne avkastningskravet til investeringer som inneholder risiko. Det er naturlig at investoren skal kompenseres for risikofri rente og selve risikoen som følger med investeringen. Risikofri rente er lang statsobligasjon (typisk 10 år) eller historisk risikofri realrente. Det er med andre ord den renten du får uten noe som helst risiko. Beta-koeffisient er markedets systematiske risiko. Altså den risikoen vi ikke får diversifisert bort. Det kan være nedgangstider, manglende likviditet og markedskollaps.
</div>

 I aksjemarkedet på Færøyene er forventet avkastning på markedsporteføljen kommende  periode 9 prosent, mens tilhørende standardavvik er 12 prosent. Forventet avkastning på 
aksjer i Fiskeoppdrett-selskapet Beidarin er 12 prosent, mens tilhørende standardavvik er 15 
prosent. Risikofri rente på Færøyene er 3 prosent med tilhørende standardavvik på 0 prosent.   

b) Hva må du gjøre for å oppnå forventet avkastning på 8 prosent på din 
porteføljeplassering i følgende tilfeller:  

1) Markedsporteføljen kombineres med risikofri posisjon 

<div class="solution">


$$
0.08 = w0.03 + (1-w)0.09 \\
w(0.03-0.09) = 0.08-0.09 \\
w(0.06) = 0.01 \\
w = 0.01/0.06 = 0.01/0.06 = 0.1667
$$
</div>

2) Aksjer i Beidarin kombineres med risikofri posisjon 

<div class="solution">

$$
0.08 = w0.03 + (1-w)0.12 \\
w(0.03-0.12) = 0.08-0.12 \\
w(0.09) = 0.04 \\
w = 0.04/0.09 = 0.44
$$
</div>


c) Finn standardavvik og beta verdien til porteføljen i de to tilfellene beskrevet over. Gi  en verbal forklaring på hvorfor de to risikomålene varierer mellom de to porteføljene.  

<div class="solution">
Standardavviket er gitt ved
$$
Std(r_m) = (1-0.1665)12 = 10\\
Std(r_b) = (1-0.44)15 = 8.33 
$$

Selskapets beta fremkomer som
$$
0.12=0.03+\beta_b\cdot (0.09-0.03) \Leftrightarrow \\
\beta_b = (0.12-0.03)/(0.09-0.03) = 1.5
$$
Mens markedsporteføljens alltid vil være
$$
\beta_m =1
$$
</div>

d) Anta at Beidarin aksjen i dag handles for 190 kroner. Hvis beta verdien på Beidarin  aksjen er 1,5 hvilken kurs vil du predikerer på Beidarin aksjen om ett år?  

<div class="solution">
Vi har følgende sammenheng
$$
(P_1-190)/190=0.12 \Leftrightarrow \\
P_1=1.12\cdot190 = 212
$$
</div>

e) Anta at utviklingen i økonomien svekkes slik at risikofrirente faller til 1 prosent.  
Hvordan påvirker det predikert kurs på Beidarin aksjen? Gi en verbal forklaring på 
hvorfor predikert aksjekurs på Beidarin aksjen endres av at risikofrirente faller.     

<div class="solution">
Den forventede avkastningen øker fra 0.12 til
$$
0.13=0.01+1.5\cdot(0.09-0.01)
$$
Noe som betyr at aksjekursen øker. Risikpremien øker, og siden beta større enn 1 fører høere risikokrav
</div>

 
# Oppgave 4: Emisjoner og tegningsretter (Teller 10 prosent) 

Selskapet Nordic Oil har i dag en egenkapital på 1 500 000 kroner og aksjekursen er i dag 15 
kroner, og det er tidligere utstedt 100 000 aksjer. Selskapet skal nå hente inn 500 000 i ny 
aksjekapital ved å utstede 50 000 nye aksjer til en emisjonskurs på 10 kr.  

a) Finn verdien av en tegningsrett i emisjonen til Nordic Oil.   

<div class="solution">
$$
N = n/m = 100000/50000 = 2 \\
T_x = \frac{15-10}{2+1} = 5/3 = 1.666
$$
</div>


b) Gi en verbal forklaring på hvorfor emisjonskursen ikke har betydning for 
aksjonærverdiene til gamle aksjonærer i Nordic Oil når aksjonærene selger sine 
tegningsretter.   

<div class="solution">
Verdien av tegningsrettigheten vil nøyaktig tilsvare kursfallet etter at tegningsrettigheten er
utløpt. Gamle aksjonærers formue vil derfor være helt upåvirket av emisjonen såframt man selger 
tegningsrettigheten i markedet.
</div>

# Oppgave 5: Opsjoner (Teller 10 prosent) 

Du er ansatt som økonomisjef i det private oljeselskapet Norway Oil, hvor hoveddelen av 
inntekten er relatert til salget av råolje som prises i USD. Selskapet har hovedkontor og 
produksjon i Norge. Det er du som tar beslutningen om deler av oljeproduksjonen skal sikres 
eller ikke ved hjelp av derivater. 

a) Gi en verbal tolkning av hvilke risikofaktorer selskapet er eksponert mot 

<div class="solution">
- Valutakursrisiko siden salg av råolje er priset i USD.
- Prisrsiko siden prisen på råolje (råvare) typisk vil ha sterke svingninger over tid.
</div>


b) Du har forhandlet deg frem til en solid bonusavtale basert på neste års resultat. Gitt at 
du bare tenker på deg selv, forklar om du ville valgt å sikre mye eller lite av 
oljeproduksjonen. Ville dette valget endret seg om bonusen var basert på snittet av 
resultatet for de neste fem årene? 

<div class="solution">
- Ett år: Sikre lite av oljeproduksjonen, det kan gi svært høy bonus dersom prisrisikokompnentene gir høy inntekt, og ingen intekt dersom prisrisikokompnentene går i motsatt retning.\\
- Fem år:  Siden snittet vil avhenge av alle fem år, vil det kunne være  fordelaktig å unngå konkur i løpet av perioden. Dette kan gjøres ved å sikre mer.
</div>


c)  Etter en grundig analyse, velger du kun å sikre deg mot oljeprisnedgang. Hvilke 
derivater ville du vurdert? Og hva vil hovedkriteriene for det endelige valget av 
derivat være? 

<div class="solution">
Finansielle derivater gjenomgått i dette kurset som påvirker kontantstrømmen består av.

- Opsjoner
- Futures 
- Forwards 
- Swaps

Kriteriet for det endelig valget: Asymetrisk, dvs. oppnå en positiv kontantstrøm fra derivatetet i det tilfelle det underliggende objektet i form av råoljeprisen går ned. Kan gjørs ved en salgsopsjon på råoljeprisen, $Max(0,I-O_T)$.
Eventuelt sikre dette i form futurekontrakt på valutakursen.
</div>



